name:
    css: '#productTitle'
    type: Text

product_overview:
    css: '#productOverview_feature_div tr'
    multiple: true
    type: Text
    children:
        info: 
            css: 'td.a-span3 .a-size-base.a-text-bold'
            type: Text
        value:
            css: 'td.a-span9 .a-size-base' #.a-size-base'
            type: Text

product_tech_spec:
    css: '#productDetails_techSpec_section_1 tr'
    multiple: true
    type: Text
    children:
        info:
            css: th
            type: Text
        value:
            css: td
            type: Text

product_tech_spec2:
    css: '#productDetails_techSpec_section_2 tr'
    multiple: true
    type: Text
    children:
        info:
            css: th
            type: Text
        value:
            css: td
            type: Text

product_info:
    css: '#prodDetails tr'
    multiple: true
    type: Text
    children:
        info:
            css: 'th.a-size-base.prodDetSectionEntry'
            type: Text
        value:
            css: 'td.a-size-base.prodDetAttrValue'
            type: Text

            
seller:
    css: '#sellerProfileTriggerId'
    type: Text

seller_link:
    css: '#sellerProfileTriggerId'
    type: Link

seller2:
    css: '#bylineInfo'
    type: Text
seller_link2:
    css: '#bylineInfo'
    type: Link

freq_bought:
    css: '#sims-fbt-form .a-size-base.a-link-normal' #'#sims-fbt-checkbox-label span' 
    type: Text

freq_bought_link:
    css: '#sims-fbt-form .a-size-base.a-link-normal'
    type: Link

freq_bought_2_info:
    css: 'div.sims-fbt-checkbox-label'
    multiple: true
    type: Text
    children:
        info:
            css: '.a-size-base.a-link-normal'
            type: Text
        value:
            css: '.a-size-base.a-link-normal'
            type: Link

customer_reviews:
    css: ''
    multiple: true
    type: Text
    children:
        info:
            css: '#acrPopover .a-declarative'
            type: Text
        value: 
            css: '#acrCustomerReviewText'
            type: Text

customer_reviews_detail: 
    css: '#histogramTable tr'
    multiple: true
    type: Text
    children:
        info:
            css: 'td.aok-nowrap .a-link-normal'
            type:  Text
        info2:
            css: 'td.aok-nowrap .a-size-base'
            type:  Text
        value:
            css: 'td.a-text-right.a-nowrap .a-size-base'
            type: Text

best_seller_rank:
    css: '#productDetails_detailBullets_sections1 tr td .a'
    type: Text

link_to_all_reviews:
    css: '#cr-pagination-footer-0 .a-text-bold' #'div.card-padding a.a-link-emphasis'
    type: Link

link_to_all_reviews2:
    css: 'div.review-medley-footer div.a-row.a-spacing-medium.a' #'div.card-padding a.a-link-emphasis'
    type: Link

# none of these for link_to_all_reviews is working..

# link_to_all_reviews2:
#     css: '#cr-pagination-footer-0' #'div.card-padding a.a-link-emphasis'
#     type: Link

# link_to_all_reviews3:
#     css: '#cr-pagination-footer-0 .see-all-reviews-link-foot' #'div.card-padding a.a-link-emphasis'
#     type: Link

# link_to_all_reviews4:
#     css: '#cr-pagination-footer-0 .a-link-emphasis a-text-bold selectorgadget_selected'
#     type: Link

# link_to_all_reviews5:
#     css: '#cr-pagination-footer-0 .a-link-emphasis' #'div.card-padding a.a-link-emphasis'
#     type: Link

# link_to_all_reviews6:
#     css: '#cr-pagination-footer-0' #'div.card-padding a.a-link-emphasis'
#     type: attribute
#     attribute: data-hook