# -*- coding: utf-8 -*-
"""JSON_session.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14cYI51Xidj7x3efXdiSpEIqtimtHt8sJ
"""

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

import pandas as pd

thisdict['brand']

list1 = [2,3,4,5,'name']

list1[0]

[{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
},
 
 {
  "brand": "BMW",
  "model": "X5",
  "year": 1998
}]

df = pd.read_json('https://gbfs.capitalbikeshare.com/gbfs/en/free_bike_status.json')

df.iloc[0,:]

lat =  []
lon = []
for i in df['data']['bikes']:
    lat.append(i['lat'])
    lon.append(i['lon'])

print(lon)

len(lat)

df = pd.DataFrame(index = range(len(lat)))

df['Latitude'] = lat

df['Longitude'] = lon

df

"""**Creation of last week data**"""

df1 = pd.read_csv('/content/202101-capitalbikeshare-tripdata.csv')

df1.started_at = pd.to_datetime(df1.started_at)
df1 = df1[df1['started_at'] >'2021-01-25']
df1.index = df1.started_at
df1 = df1.sort_index()

df1['day'] = df1['started_at'].dt.date
df1['hour'] = df1['started_at'].dt.hour

df2 = df1.groupby(by = ['day', 'hour', 'member_casual']).count()['ride_id'].reset_index()
df2.columns = ['day', 'hour', 'member_type', 'count']

df2

df2.to_csv('last_week.csv')

